import Head from "next/head";
import Link from "next/link";
import React, { useEffect, useState } from "react";


export default function Home() {

  const [message, setMessage] = useState("loading!!")

  useEffect(() => {
    fetch("http://localhost:8080/").then(
      response => response.json()
    ).then(
      data => {
        console.log(data.message);
        setMessage(data.message)
      }
    )
  }, [])

  return (
    <>
      <Head>
        <title>ShopClues</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <img src="/home.webp" alt="home" />
        <section className="text-gray-600 body-font">
          <div className="container px-5 py-24 mx-auto">
            <div className="flex flex-wrap w-full mb-20 flex-col items-center text-center">
              <h1 className="sm:text-3xl text-2xl font-medium title-font mb-2 text-gray-900">Wear the code with shopcluse.com</h1>
              <p className="lg:w-1/2 w-full leading-relaxed text-gray-500">Wear whatever you want? What do you want? You want code? So why not wear the code??</p>
              <p className="lg:w-1/2 w-full leading-relaxed text-gray-500">Wear whatever you want? What do you want? You want code? So why not wear the code??</p>
              <p className="lg:w-1/2 w-full leading-relaxed text-gray-500">Wear whatever you want? What do you want? You want code? So why not wear the code??</p>
            </div>

            <div className="flex flex-wrap -m-4">
              <div className="xl:w-1/3 md:w-1/2 p-4">
                <Link href={'/tshirt'}>
                  <div className="border border-gray-200 p-6 rounded-lg flex">
                    <div>
                      <img src="tshirt.jpg" alt="" />
                    </div>
                    <div className="mx-2">
                      <h2 className="text-lg text-gray-900 font-medium title-font mb-2">T-shirts</h2>
                      <p className="leading-relaxed text-base">Up to 60% off on Branded T-Shirts</p>
                    </div>
                  </div>
                </Link>
              </div>
              <div className="xl:w-1/3 md:w-1/2 p-4">
                <Link href={'/hoodie'}>
                  <div className="border border-gray-200 p-6 rounded-lg flex">
                    <div>
                      <img className="h-[110px]" src="hoodie.webp" alt="" />
                    </div>
                    <div className="mx-2">
                      <h2 className="text-lg text-gray-900 font-medium title-font mb-2">Hoodies</h2>
                      <p className="leading-relaxed text-base">Up to 60% off on All type of hoodies</p>
                    </div>
                  </div>
                </Link>
              </div>
              <div className="xl:w-1/3 md:w-1/2 p-4">
                <Link href={'/shoes'}>
                  <div className="border border-gray-200 p-6 rounded-lg flex">
                    <div>
                      <img className="h-[110px]" src="shoes.jpg" alt="" />
                    </div>
                    <div className="mx-2">
                      <h2 className="text-lg text-gray-900 font-medium title-font mb-2">Shoes</h2>
                      <p className="leading-relaxed text-base">Top rated products from new sellers</p>
                    </div>
                  </div>
                </Link>
              </div>
              <div className="xl:w-1/3 md:w-1/2 p-4">
                <Link href={'/mobile'}>
                  <div className="border border-gray-200 p-6 rounded-lg flex">
                    <div>
                      <img className="h-[110px]" src="mobile.jpg" alt="" />
                    </div>
                    <div className="mx-2">
                      <h2 className="text-lg text-gray-900 font-medium title-font mb-2">Smart Phones</h2>
                      <p className="leading-relaxed text-base">New launches are available Checkout !!</p>
                    </div>
                  </div>
                </Link>
              </div>
              <div className="xl:w-1/3 md:w-1/2 p-4">
                <Link href={'/airdopes'}>
                  <div className="border border-gray-200 p-6 rounded-lg flex">
                    <div>
                      <img className="h-[110px]" src="airdopes.jpg" alt="" />
                    </div>
                    <div className="mx-2">
                      <h2 className="text-lg text-gray-900 font-medium title-font mb-2">Airdopes</h2>
                      <p className="leading-relaxed text-base">Keep shopping for</p>
                    </div>
                  </div>
                </Link>
              </div>
              <div className="xl:w-1/3 md:w-1/2 p-4">
                <Link href={'/watches'}>
                  <div className="border border-gray-200 p-6 rounded-lg flex">
                    <div>
                      <img className="h-[110px]" src="watch.jpg" alt="" />
                    </div>
                    <div className="mx-2">
                      <h2 className="text-lg text-gray-900 font-medium title-font mb-2">Watches</h2>
                      <p className="leading-relaxed text-base">Customers’ Most-Loved Fashion for you</p>
                    </div>
                  </div>
                </Link>
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  )
}
